# Server Port
server.port=8080

# MySQL Database Configuration (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Hibernate Settings (Clean & Professional)
spring.jpa.hibernate.ddl-auto=update
# show-sql false করছি যাতে ডুপ্লিকেট না হয়, আমরা লগার দিয়ে দেখব
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# Logging & Debugging
logging.level.org.springframework.web=DEBUG
# SQL কুয়েরি দেখার জন্য
logging.level.org.hibernate.SQL=DEBUG
# কুয়েরির ভেতরের ভ্যালু (Parameters) দেখার জন্য
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Project Settings
spring.main.allow-circular-references=true
project.image=images/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
