plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.mrahmed.myocr'
    compileSdk 35

    defaultConfig {
        applicationId "com.mrahmed.myocr"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    // Android core libraries
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    // Firebase BoM (Updated to the latest version)
    implementation platform('com.google.firebase:firebase-bom:33.10.0')

    // Firebase Firestore (Managed by BOM - no need to specify version)
    implementation 'com.google.firebase:firebase-firestore'
    // Firebase Analytics (Managed by BOM - no need to specify version)
    implementation 'com.google.firebase:firebase-analytics'

    // ML Kit for Text Recognition (Updated to the latest version)
    implementation 'com.google.mlkit:text-recognition:16.0.1'
    // Bengali model
    implementation 'com.google.android.gms:play-services-mlkit-text-recognition-devanagari:16.0.1'

    implementation libs.firebase.database
    implementation libs.swiperefreshlayout
    implementation libs.media3.common
    implementation libs.navigation.fragment
    implementation libs.navigation.ui

    // Unit Testing Dependencies
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    implementation("com.davemorrissey.labs:subsampling-scale-image-view:3.10.0")

    // Google Play Services (Updated to the latest version)
    implementation("com.google.android.gms:play-services-basement:18.5.0")
    implementation("com.google.android.gms:play-services-base:18.5.0")
    implementation("com.google.android.gms:play-services-tasks:18.2.0")

    //Save Scan data to Google or Microsoft
    implementation 'org.apache.poi:poi:5.2.3'
    implementation 'org.apache.poi:poi-ooxml:5.2.3'

}